#!/usr/bin/env bash
# this script transfers a file from our client to a server using scp.

# check if the number of paramerters is less than 4
if [ $# -lt 4]; then
	# display the usage message and exit
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assign the parameters to variables
FILE=$1
IP=$2
USER=$3
KEY=$4

# transfer the file to the user home directory using scp
# disable the strict host key checking option
scp -o StrictHostKeyChecking=no -i "$KEY" "$FILE" "$USER@$IP:~/"

# exit with the status code of scp command
exit $?
