#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server

# Update system packages
sudo apt update
sudo apt upgrade -y

# Install HAProxy
sudo apt install haproxy -y

# Configure HAProxy
sudo tee -a /etc/haproxy/haproxy.cfg <<EOF
frontend http_front
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 325720-web-01 3.80.19.226:80 check
    server 325720-web-02 18.233.65.210:80 check
EOF

# Restart HAProxy
sudo systemctl restart haproxy
