#!/usr/bin/env bash
# This script fixes the Nginx configuration to listen on port 80 of all IPv4 IPs
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
