#!/usr/bin/env bash
# This script creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal.

pid=$(pgrep -f "$0")
echo "$pid" > /var/run/myscript.pid

trap "echo Y U no love me?!" INT
trap "echo I hate the kill command" TERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done

rm /var/run/myscript.pid
exit
