#!/usr/bin/env bash
# This script print numbers from 1 to 20 but display bad luck from China with 4th
# diplays bad luck from Japan with 9th, bad luck from Italy with 17th

i=1
while (( i <= 20))
do
	case $i in
		4)
			echo "$i"
			echo "bad luck from China"
			;;
		9)
			echo "$i"
                        echo "bad luck from Japan"
                        ;;
		17)
			echo "$i"
                        echo "bad luck from Italy"
                        ;;
		*)
			echo "$i"
			;;
	esac
	(( i++))
done
