#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf # Change user from www-data to nginx
sed -i "s/80/8080/g" /etc/nginx/sites-available/default # Change port number from 80 to 8080
chmod 644 /etc/nginx/nginx.conf # Make file readable by owner, group, and others
pkill apache2 # Kill apache2 process
sudo -u nginx service nginx start # Start nginx service as nginx user
